server:
  port: 9050
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false
